apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
      - name: client-deployment
        image: client
        imagePullPolicy: Never # Use the local image
        resources:
          requests:
            memory: "64Mi" # Guaranteed memory allocation
            cpu: "250m" # Guaranteed CPU allocation (250 millicores = 0.25 CPU)
          limits:
            memory: "128Mi" # Maximum memory usage
            cpu: "500m"
        ports:
        - containerPort: 80
