apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-deployment
  template:
    metadata:
      labels:
        app: react-deployment
    spec:
      containers:
        - name: react-container
          image: client
          resources:
            requests:
              memory: "64Mi"  # Guaranteed memory allocation
              cpu: "250m"     # Guaranteed CPU allocation (250 millicores = 0.25 CPU)
            limits:
              memory: "128Mi" # Maximum memory usage
              cpu: "500m"
          ports:
            - containerPort: 80
